### ISSUE TITLE
Review del desafío

### ISSUE THREAD

**Issue by tobiasfacello** [martin7682/desafio-modulo-4#1]
Hola Martin, desde ya felicidades por haber llegado hasta el desafío.
Por lo que ví, y es algo que casi se me escapa cabe destacar, es que no usaste el CMS para mostrar los proyectos de tu portfolio. Por ende, y para que cumplas con la consigna del desafío, creo que necesita ajustes.
Pienso que es la manera correcta de evaluar este desafío, así que éxitos con eso y cuando lo tengas listo... enseguida te lo voy a estar aprobando (o de no ser yo, algún otro estudiante que haga la review). Saludos.

**Comment by martin7682** [comment]
Hola Tobias, primero, gracias por evaluar mi desafío! Para comprobar la observación, procedí a modificar y agregar contenido al Portfolio desde ContentFul y la misma se vio reflejada automáticamente en la web del Portfolio.
Podrías darme más detalles acerca de cuál es el ajuste a realizar?

**Comment by tobiasfacello** [comment]
Buenas tardes Martin! Te pido disculpas, ahi me puse a mirar más a detalle tu código y no tiene errores, di por sentado que no estabas usando el CMS como eran elementos genéricos con un Lorem de por medio, así que reconozco el fallo por mi parte y te pido mil disculpas... Todo está correcto al parecer así que **LGTM**. Gracias por tomarte la review con la mejor onda y corroborar, el fallo fue mío. Un abrazo y mucho éxito en el próximo módulo! 🚀
